### ISSUE TITLE
error ？？

### ISSUE THREAD

**Issue by jiagh2010** [tkat0/PyTorch_BlazeFace#7]
I'm just using examples！！

Traceback (most recent call last):
  File "1.py", line 5, in <module>
    h = BlazeFace(x)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by RealBBakGosu** [comment]
Same error to me.

**Comment by njustymk** [comment]
Same error to me.

**Comment by shimiaoli** [comment]
shouldn't it be 
 net = BlazeFace()
 h = net(x)

**Comment by tkat0** [comment]
Thank you. The README was wrong.
Fixed #11
